### Ambil Semua Ruangan
GET http://localhost:5160/api/rooms

### Tambah Ruangan Baru
POST http://localhost:5160/api/rooms
Content-Type: application/json

{
  "name": "Ruang Gaming Pro",
  "capacity": 5
}

### Tambah Booking Baru
POST http://localhost:5160/api/bookings
Content-Type: application/json

{
  "roomId": 3,
  "userEmail": "mahasiswa.ambis@pbl.com",
  "startTime": "2026-02-15T08:00:00",
  "endTime": "2026-02-15T12:00:00"
}

### Tambah Customer Baru
POST http://localhost:5160/api/customers
Content-Type: application/json

{
  "name": "Pratama",
  "email": "pratama@pbl.com",
  "phoneNumber": "081234567892"
}

### Hapus Customer ID 1
DELETE http://localhost:5160/api/customers/1

### Cek Data Awal (GET)
GET http://localhost:5160/api/bookings

### Tes Booking bentrok
POST http://localhost:5160/api/bookings
Content-Type: application/json

{
  "roomId": 1,
  "customerId": 3,
  "startTime": "2026-02-10T14:00:00",
  "endTime": "2026-02-10T16:00:00"
}

### Register Admin Baru
POST http://localhost:5160/api/auth/register
Content-Type: application/json

{
  "username": "candraadminpbl2026",
  "password": "candragantengbanget"
}

### Test Login Admin
POST http://localhost:5160/api/auth/login
Content-Type: application/json

{
  "username": "candraadminpbl2026",
  "password": "candragantengbanget"
}

### auth baru eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiY2FuZHJhYWRtaW5wYmwyMDI2IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTc3MDkwMTg5MywiaXNzIjoiUGVtaW5qYW1hblJ1YW5nYW5CYWNrZW5kIiwiYXVkIjoiUGVtaW5qYW1hblJ1YW5nYW5BcHAifQ.AWO5A3mAQlBjvLe_d67z9K7MS4ZJ85K7L07CoNatgmc

### Tes hapus ruangan pake akun user
DELETE http://localhost:5160/api/rooms/2
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcjEyMzQ1IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiI3IiwiaWQiOiI3IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTc3MDkxNTE4NiwiaXNzIjoiUGVtaW5qYW1hblJ1YW5nYW5CYWNrZW5kIiwiYXVkIjoiUGVtaW5qYW1hblJ1YW5nYW5BcHAifQ.Vz_bpnGcQdfilJfge9HkUMbu-U3Rpy0H8zwomasYqUA

### Tes hapus ruangan pake akun admin
DELETE http://localhost:5160/api/rooms/1
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzMTIzNDUiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjYiLCJpZCI6IjYiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTc3MDkxNTMxMiwiaXNzIjoiUGVtaW5qYW1hblJ1YW5nYW5CYWNrZW5kIiwiYXVkIjoiUGVtaW5qYW1hblJ1YW5nYW5BcHAifQ.wN_CJ4ry1US0TJRBqkIg3tupqvnONXkWkx7V2TKCB7Y