### Ambil Semua Ruangan
GET http://localhost:5160/api/rooms

### Tambah Ruangan Baru
POST http://localhost:5160/api/rooms
Content-Type: application/json

{
  "name": "Ruang Gaming Pro",
  "capacity": 5
}

### Tambah Booking Baru
POST http://localhost:5160/api/bookings
Content-Type: application/json

{
  "roomId": 3,
  "userEmail": "mahasiswa.ambis@pbl.com",
  "startTime": "2026-02-15T08:00:00",
  "endTime": "2026-02-15T12:00:00"
}

### Tambah Customer Baru
POST http://localhost:5160/api/customers
Content-Type: application/json

{
  "name": "Pratama",
  "email": "pratama@pbl.com",
  "phoneNumber": "081234567892"
}

### Hapus Customer ID 1
DELETE http://localhost:5160/api/customers/1

### Cek Data Awal (GET)
GET http://localhost:5160/api/bookings

### Tes Booking bentrok
POST http://localhost:5160/api/bookings
Content-Type: application/json

{
  "roomId": 1,
  "customerId": 3,
  "startTime": "2026-02-10T14:00:00",
  "endTime": "2026-02-10T16:00:00"
}

### Register Admin Baru
POST http://localhost:5160/api/auth/register
Content-Type: application/json

{
  "username": "candraadminpbl2026",
  "password": "candragantengbanget"
}