// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2026_peminjaman_ruangan_backend.Data;

#nullable disable

namespace _2026_peminjaman_ruangan_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260209195154_SeedInitialBooking")]
    partial class SeedInitialBooking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_2026_peminjaman_ruangan_backend.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndTime = new DateTime(2026, 2, 10, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 1,
                            StartTime = new DateTime(2026, 2, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            UserEmail = "candra@pdbl.com"
                        },
                        new
                        {
                            Id = 2,
                            EndTime = new DateTime(2026, 2, 11, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 2,
                            StartTime = new DateTime(2026, 2, 11, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            UserEmail = "putra@pdbl.com"
                        });
                });

            modelBuilder.Entity("_2026_peminjaman_ruangan_backend.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 20,
                            Name = "Ruang Rapat Utama"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 40,
                            Name = "Lab Komputer 1"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 100,
                            Name = "Auditorium Mini"
                        });
                });

            modelBuilder.Entity("_2026_peminjaman_ruangan_backend.Models.Booking", b =>
                {
                    b.HasOne("_2026_peminjaman_ruangan_backend.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });
#pragma warning restore 612, 618
        }
    }
}
